name: ${project.name}
main: com.olziedev.skillranks.SkillRanks
version: ${project.version}
author: Olzie
description: Grants ranks based on the numeric value of PlaceholderAPI placeholders.
api-version: '1.20'
depend: [PlaceholderAPI]
